name: formz_riverpod
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  formz: null
  freezed_annotation: null
  i18n_extension: null
  equatable: ^2.0.0
  hooks_riverpod:
  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: null
  build_runner: null





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
